---
builds:
  - id: flowx
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: flowx
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/ai-flowx/flowx/config.Build={{.Date}} -X github.com/ai-flowx/flowx/config.Commit={{.Commit}} -X github.com/ai-flowx/flowx/config.Version={{.Version}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
