cache:
  provider: cachex
  url: http://127.0.0.1:8081
gpt:
  provider: openai
  api: https://openai.com/api
  token: token
memory:
  type: shortterm
store:
  provider: ragx
  url: http://127.0.0.1:8082
  path: /path/to/file
tool:
  - name: decorator
  - name: hello
  - name: structuredtool
  - name: wechat
