cache:
  provider: cachex
  host: 127.0.0.1
  port: 8081
  user: user
  pass: pass
flow:
  channel: wechat
gpt:
  provider: doubao-chat
  api: https://ark.cn-beijing.volces.com/api/v3/chat/completions
  model: ep-*
  key: 8429f8ab-*
memory:
  type: shortterm
store:
  provider: vecx
  host: 127.0.0.1
  port: 8082
  path: /path/to/file
  user: user
  pass: pass
tool:
  - name: decorator
  - name: gerrit
  - name: hello
  - name: structuredtool
