cache:
  provider: cachex
  api: http://127.0.0.1:8081
  token: token
gpt:
  provider: openai
  api: https://openai.com/api
  token: token
store:
  provider: ragx
  api: http://127.0.0.1:8082
  token: token
