cache:
  provider: cachex
  url: http://127.0.0.1:8081
flow:
  channel: wechat
gpt:
  provider: doubao-chat
  api: https://ark.cn-beijing.volces.com/api/v3/chat/completions
  model: ep-*
  key: 8429f8ab-*
memory:
  type: shortterm
store:
  provider: ragx
  url: http://127.0.0.1:8082
  path: /path/to/file
tool:
  - name: decorator
  - name: gerrit
  - name: hello
  - name: structuredtool
