---
name: "release"

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AI_FLOWX_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.23"
      - name: Run install
        run: make install
      - name: Unshallow
        run: git fetch --prune --unshallow
        continue-on-error: false
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.AI_FLOWX_TOKEN }}
      - name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.AI_FLOWX_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: craftslab/flowx:latest
